require 'xsd_reader/shared'
require 'xsd_reader/xml'
require 'xsd_reader/schema'
require 'xsd_reader/element'
require 'xsd_reader/attribute'
require 'xsd_reader/sequence'
require 'xsd_reader/choice'
require 'xsd_reader/complex_type'
require 'xsd_reader/simple_content'
require 'xsd_reader/complex_content'
require 'xsd_reader/extension'
require 'xsd_reader/import'
require 'xsd_reader/simple_type'

